build-blu_spark-kernel

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,67 +1,276 @@
-name: ci
+name: Build Kernel
 on:
   push:
-    branches: main
-  pull_request:
+    branches: build-OPlus8T
+
   workflow_dispatch:
   
 jobs:
-  yaml-check:
+  build:
+    name: Build Kernel by ${{ github.actor }}
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
+    env:
+      kernel-url: https://github.com/Sauvio/OPlus8T
+      kernel-dir: kernel
+      branch: blu_spark-custom-11
+      config: blu_spark_defconfig
+      arch: arm64
+      aosp-gcc: true
+      aosp-clang: true
+      ksu: true
+      ksu-version: main
+      anykernel3: true
+      android-version: 11
+      aosp-clang-version: r370808
+      python-27: true
+      disable-lto: true
+      overlayfs: true
+      lxc: false
+      lxc-patch: false
     steps:
-
-    - name: Checkout Repo
-      uses: actions/checkout@v4
-
-    - name: Install Node.js
-      uses: actions/setup-node@v3
-      with:
-       node-version: 20
-
-    - name: Imstall yamllint
-      run: sudo npm i -g yaml-lint
-
-    - name: Check yaml
-      run: /usr/local/lib/node_modules/yaml-lint/dist/cli.js action.yml
-
-  ci-test:
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - os: ubuntu-latest
-          id: latest
-
+      - uses: actions/checkout@v3
+      # - id: cleanup
+      #   uses: rokibhasansagar/slimhub_actions@main
+        
+      # - name: install package
+      #   shell: bash
+      #   run: sudo apt install -y binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3
+  
+      # - name: download aosp-gcc
+      #   shell: bash
+      #   if: inputs.aosp-gcc == 'true'
+      #   run: |
+      #     if [ ${{ inputs.aosp-clang }} = true ]; then
+      #         mkdir -p -v $HOME/gcc-64
+      #         wget -q -O gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
+      #         tar -C $HOME/gcc-64 -zxf gcc-aarch64.tar.gz
+      #         mkdir -p -v $HOME/gcc-32
+      #         wget -q -O gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
+      #         tar -C $HOME/gcc-32 -zxf gcc-arm.tar.gz
+      #     else
+      #         git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-64
+      #         git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/ --depth=1 -b android${{ inputs.android-version }}-release $HOME/gcc-32
+      #     fi
+  
+      # - name: download Android-NDK
+      #   if: inputs.android-ndk == 'true'
+      #   shell: bash
+      #   run: |
+      #     if [ ${{ inputs.aosp-gcc }} = false ]; then
+      #         echo
+      #         if [ ${{ inputs.android-ndk-x64 }} = false ]; then
+      #             wget -q -O android-ndk.zip https://dl.google.com/android/repository/android-ndk-${{ inputs.android-ndk-version }}-linux.zip
+      #             unzip -q -d $HOME android-ndk.zip
+      #         else
+      #             wget -q -O android-ndk.zip https://dl.google.com/android/repository/android-ndk-${{ inputs.android-ndk-version }}-linux-x86_64.zip
+      #             unzip -q -d $HOME android-ndk.zip
+      #         fi
+      #         echo
+      #     else
+      #         echo "Please disable aosp-gcc and aosp-clang."
+      #         exit 127
+      #     fi
           
-    needs: yaml-check
-    runs-on: ${{ matrix.os }}
-    permissions:
-      contents: write
-
-    steps:
-
-    - name: Checkout Repo
-      uses: actions/checkout@v4
-
-    - name: Test CI
-      uses: Sauvio/dabao-kernel_build_action@main
-      with: 
-          kernel-url: https://github.com/Sauvio/OPlus8T
-          kernel-dir: kernel
-          branch: blu_spark-custom-11
-          config: blu_spark_defconfig
-          arch: arm64
-          aosp-gcc: true
-          aosp-clang: true
-          ksu: true
-          ksu-version: main
-          anykernel3: true
-          android-version: 11
-          aosp-clang-version: r370808
-          python-27: true
-          disable-lto: true
-          overlayfs: true
-          lxc: false
-          lxc-patch: false
+      #     export HOMES=$(pwd) 
+      #     export LLVMS=$HOME/android-ndk-${{ inputs.android-ndk-version }}/toolchains/llvm/prebuilt/linux-x86_64/bin
+      #     cd $LLVMS
+      #     for file in $(ls llvm-*); do
+      #     ln -s "$file" "aarch64-linux-android$(( ${{ inputs.android-version }} + 19 ))-${file#llvm-}"
+      #     done
+      #     cd $HOMES
+  
+  
+      # - name: use python 2.7
+      #   if: inputs.python-27 == 'true'
+      #   run: |
+      #     sudo apt install -y -q python2.7 python2.7-minimal
+      #     sudo rm /bin/python
+      #     sudo ln -s /bin/python2.7 /bin/python
+      #     sudo ln -s /bin/python2.7 /bin/python2
+      #   shell: bash
+  
+      # - name: download aosp clang
+      #   if: inputs.aosp-clang == 'true'
+      #   run: |
+      #     if [ ${{ inputs.aosp-gcc }} = true ]; then
+      #         mkdir $HOME/clang -p -v 
+      #         wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android${{ inputs.android-version }}-release/clang-${{ inputs.aosp-clang-version }}.tar.gz
+      #         tar -C $HOME/clang -zxf clang-${{ inputs.aosp-clang-version }}.tar.gz
+      #     else
+      #         echo "Please enable aosp-gcc."
+      #         exit 127
+      #     fi
+      #   shell: bash
+  
+      - name: pull kernel source from selected branch
+        run: |
+          git clone ${{ inputs.kernel-url }} -b "${{ inputs.branch }}" --depth=1 ${{ inputs.kernel-dir }}
+          git checkout 06d21b483ed3d719c8a08deb90ced593847dc469
+        shell: bash
+  
+      - name: pull vendor source
+        if: inputs.vendor == 'true'
+        run: |
+          git clone ${{ inputs.vendor-url }} --depth=1 ${{ inputs.vendor-dir }}
+        shell: bash
+  
+      - name: Setup ccache 
+        if: inputs.ccache == 'true' 
+        uses: hendrikmuhs/ccache-action@v1.2 
+        with: 
+          key: build-kernel-${{ inputs.arch }}${{ inputs.config }} 
+          max-size: 4G
+  
+      - name: Set swap space
+        uses: pierotofy/set-swap-space@master 
+        with: 
+          swap-size-gb: 12
+     
+      - name: pull kernelsu
+        if: inputs.ksu == 'true'
+        run: |
+          cd ${{ inputs.kernel-dir }}
+          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ inputs.ksu-version }}
+        shell: bash
+  
+      - name: disable lto
+        if: inputs.disable-lto == 'true'
+        shell: bash
+        run: |
+          cd ${{ inputs.kernel-dir }}
+          if grep -q "LTO" "arch/${{ inputs.arch }}/configs/${{ inputs.config }}"
+          then
+               sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ inputs.arch }}/configs/${{ inputs.config }} 
+               sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/${{ inputs.arch }}/configs/${{ inputs.config }} 
+               sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/${{ inputs.arch }}/configs/${{ inputs.config }} 
+               echo "CONFIG_LTO_NONE=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+          fi
+  
+      - name: enable overlayfs
+        if: inputs.overlayfs == 'true'
+        shell: bash
+        run: |
+          cd ${{ inputs.kernel-dir }}
+          grep -q "OVERLAY_FS" "arch/${{ inputs.arch }}/configs/${{ inputs.config }}" || echo "CONFIG_OVERLAY_FS=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+        
+      - name: enable kvm
+        if: inputs.kvm == 'true'
+        shell: bash
+        run: |
+          cd ${{ inputs.kernel-dir }}
+          echo "CONFIG_VIRTUALIZATION=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+          echo "CONFIG_KVM=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+          echo "CONFIG_KVM_MMIO=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+          echo "CONFIG_KVM_ARM_HOST=y" >> arch/${{ inputs.arch }}/configs/${{ inputs.config }}
+  
+      - name: enable lxc
+        if: inputs.lxc == 'true'
+        shell: bash
+        run: |
+           cd ${{ inputs.kernel-dir }}
+           wget https://github.com/wu17481748/lxc-docker/raw/main/LXC-DOCKER-OPEN-CONFIG.sh
+           bash LXC-DOCKER-OPEN-CONFIG.sh ${{ inputs.config }} -w
+           if [ ${{ inputs.lxc-patch }} = true ]; then
+               wget https://github.com/wu17481748/lxc-docker/raw/main/lxc.patch
+               git apply lxc.patch
+           else
+               echo skip lxc patch
+           fi
+  
+      - name: build kernel with clang
+        if: inputs.aosp-clang == 'true'
+        run: |
+          cd ${{ inputs.kernel-dir }}
+          mkdir -p -v out
+          export CLANG_PATH=$HOME/clang
+          export PATH=$CLANG_PATH/bin:$PATH
+          make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC=clang ARCH=${{ inputs.arch }} O=out ${{ inputs.config }}
+          if [ ${{ inputs.ccache }} = true ]; then
+              export USE_CCACHE=1
+              make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC="ccache clang" ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }}
+          else
+              make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- CC=clang ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }}
+          fi
+        shell: bash
+  
+      - name: build kernel with gcc
+        if: inputs.aosp-gcc == 'true'
+        run: |
+          if [ ${{ inputs.aosp-clang }} = false ]; then
+              cd ${{ inputs.kernel-dir }}
+              mkdir -p -v out
+              make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- ARCH=${{ inputs.arch }} O=out ${{ inputs.config }}
+              make -j$(nproc --all) CROSS_COMPILE=$HOME/gcc-64/bin/aarch64-linux-android- COMPILE_ARM32=$HOME/gcc-32/bin/arm-linux-androideabi- ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }} 
+          else
+              echo 
+          fi
+              
+        shell: bash
+  
+      - name: build kernel with android-ndk
+        if: inputs.android-ndk == 'true'
+        shell: bash
+        run: |
+          cd ${{ inputs.kernel-dir }}
+          mkdir -p -v out
+          export CLANG_PATH=$HOME/android-ndk-${{ inputs.android-ndk-version }}/toolchains/llvm/prebuilt/linux-x86_64
+          export PATH=$CLANG_PATH/bin:$PATH
+          make -j$(nproc --all) CROSS_COMPILE=$CLANG_PATH/bin/llvm- COMPILE_ARM32=$CLANG_PATH/bin/llvm- CLANG_TRIPLE=aarch64-linux-android$(( ${{ inputs.android-version }} + 19 ))- CC=clang ARCH=${{ inputs.arch }} O=out ${{ inputs.config }}
+          if [ ${{ inputs.ccache }} = true ]; then
+              export USE_CCACHE=1
+              make -j$(nproc --all) CROSS_COMPILE=$CLANG_PATH/bin/llvm- COMPILE_ARM32=$CLANG_PATH/bin/llvm- CLANG_TRIPLE=aarch64-linux-android$(( ${{ inputs.android-version }} + 19 ))- CC="ccache clang" ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }}
+          else
+              make -j$(nproc --all) CROSS_COMPILE=$CLANG_PATH/bin/llvm- COMPILE_ARM32=$CLANG_PATH/bin/llvm- CLANG_TRIPLE=aarch64-linux-android$(( ${{ inputs.android-version }} + 19 ))- CC=clang ARCH=${{ inputs.arch }} O=out ${{ inputs.extra-cmd }}
+          fi
+        
+  
+      - name: copy kernel
+        if: inputs.anykernel3 == 'false'
+        shell: bash
+        run: |
+          mkdir -p -v build
+          if [ -f ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.*-dtb ]; then
+             cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.*-dtb build -rv
+          elif [ -f ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.* ]; then
+             cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.* build -rv
+          else
+             cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image build -rv
+          fi
+  
+      - name: package with anykernel3
+        if: inputs.anykernel3 == 'true'
+        run: | 
+          git clone https://github.com/osm0sis/AnyKernel3
+          sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
+          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
+          sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
+          echo $(pwd)
+          if [ -f ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.*-dtb ]; then
+             cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.*-dtb AnyKernel3 -rv
+          elif [ -f ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.* ]; then
+             cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image.* AnyKernel3 -rv
+          else
+             cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/Image AnyKernel3 -rv
+          fi
+  
+          test -f ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/dtbo.img && cp ${{ inputs.kernel-dir }}/out/arch/${{ inputs.arch }}/boot/dtbo.img AnyKernel3/
+          
+          rm -rf AnyKernel3/.git* AnyKernel3/README.md
+        shell: bash
+  
+      - id: uploadi
+        if: inputs.anykernel3 == 'false'
+        uses: actions/upload-artifact@v3
+        with:
+          name: bare-compiled-kernel
+          path: build/*
+  
+      - id: uploada
+        if: inputs.anykernel3 == 'true'
+        uses: actions/upload-artifact@v3
+        with:
+          name: AnyKernel3-flasher
+          path: AnyKernel3/*
+      - name: post
+        shell: bash
+        run:  bash $GITHUB_ACTION_PATH/post.sh
