Fix: debug script

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -98,13 +98,14 @@ jobs:
           elif file $OUTPUT_FILE | grep -q "gzip compressed data"; then
             tar -xzf $OUTPUT_FILE -C "$CLANG_DIR"
           elif file $OUTPUT_FILE | grep -q "XZ compressed data"; then
-            # Check if $CLANG_DIR/bin exists in the tar archive
-            if tar -tf "$OUTPUT_FILE" | grep -q '/bin$'; then
-              # If $CLANG_DIR/bin exists, extract to $CLANG_DIR
-              tar -xf "$OUTPUT_FILE" -C "$CLANG_DIR"
+            # Extract the subdirectory under the root
+            SUBDIR=$(tar -tf "$OUTPUT_FILE" | grep -E '^clang[^/]+/$' | head -n 1)
+            if [ -n "$SUBDIR" ]; then
+              # If the subdirectory exists, extract its content to $CLANG_DIR
+              tar -xf "$OUTPUT_FILE" -C "$CLANG_DIR" --strip-components=1 "$SUBDIR"
             else
-              # If $CLANG_DIR/bin does not exist, extract to $CLANG_DIR/<subdirectory>
-              tar -xf "$OUTPUT_FILE" -C "$CLANG_DIR" --strip-components=1
+              echo "Error: Subdirectory not found in the tar archive."
+              exit 1
             fi
           else
             echo "Unknown compression format or unsupported file"
